@startuml

class blank_game {
}

blank_game --> "*" game
blank_game --> "1" game : current
blank_game --> "1" renderer
blank_game --> "1" r_game
blank_game --> "1" in
blank_game --> "1" mix

class game {
}

game *-- "1" g_dialog
game *-- "1" g_zawarudo
game *-- "*" g_lvl
game --> "1" g_lvl : current

class g_lvl {
}

g_lvl *-- "*" g_ent

class g_ent {
}

g_ent --> "0..1" img

class g_dialog {
}

class g_zawarudo {
}

class ani {
}

ani --> "1" img
ani *-- "*" ani_frm

class ani_frm {
}

ani_frm --> "*" sfx

class img {
}

img --> "1" SDL_Surface

class in {
}

class mix {
}

mix --> "1" game : current
mix --> "*" mus
mix --> "*" sfx

class mus {
}

mus --> "1" Mix_Music

class sfx {
}

sfx --> "1" Mix_Chunk

class renderer {
}

renderer --> "*" ani

class r_game {
}

r_game --> "1" renderer
r_game --> "1" game : current

@enduml
