@startuml

abstract class rec {
	+id
	..
	#refc
}

abstract class tape {
	+v[]
	__
	+open(id)
	+save(id)
	+close(id)
	+gc()
	..
	{abstract} +open_(rec, id)
	{abstract} +save_(rec, id)
	{abstract} +close_(rec, id)
}

tape --> "*" rec

class entity {
	+level_id
	+type
	+pos
	+vel
	+boxxy
	+bitmap_image_id
	+is_solid
}

entity --> "0..1" image

rec <|-- entity
tape <|-- entity_tape

class level {
	+name
	+game_id
}

level *-- "*" entity

rec <|-- level
tape <|-- level_tape

class game {
	+player_name
	+current_position
}

game *-- "*" level

rec <|-- game
tape <|-- game_tape

class image {
	+path
	..
	+sdl_image
}

image *-- "1" SDL_image

rec <|-- image
tape <|-- image_tape

class anim_frame {
	+t
	+i
	+j
}

class anim {
	+image_id
	+path
	..
	+fw
	+fh
	+framev[]
}

anim --> "1" image
anim *-- "*" anim_frame

rec <|-- anim
tape <|-- anim_tape

class entity_action_anim {
	+entity_type
	+anim_id
	+action_id
	+t1
	+t2
}

entity_action_anim --> "1" anim

rec <|-- entity_action_anim
tape <|-- entity_action_anim_tape

@enduml
